### ISSUE TITLE
not clear how to start 

### ISSUE THREAD

**Issue by EMCP** [Asquera/raspberry-devbox#1]
So I've got the virtualbox image loaded, and see it's a Ubuntu box..

How do I start developing Raspberry Pi stuff?  I thought the virtual machine would simulate a pi.. but I see the processor is still Intel.  Is the point of this box to act as a host for an emulator?

**Comment by ROunofF** [comment]
No the point of this box is to have the set of tool for cross compiling for the raspberri pi.

**Comment by EMCP** [comment]
ahhh okay..

Now I'm wondering if there's a way to virtualize the ARM / hardware of the pi.  I'll keep looking thanks.
