### ISSUE TITLE
Sudoers error after provision and can't move forward from there

### ISSUE THREAD

**Issue by ROunofF** [Asquera/raspberry-devbox#2]
The vagrant provision currently fails with some dependency error on the apt-get. And apparently that leaves the sudoers in a format (with version installed) that can't be used correctly. This currently makes the box a dead end since we can't use sudo from the vagrant user to fix anything (unless I'm wrong).

vagrant@ubuntu-10:~$ sudo -l

> > > /etc/sudoers: syntax error near line 4 <<<
> > > .....
> > > /etc/sudoers: syntax error near line 24 <<<
> > > sudo: parse error in /etc/sudoers near line 4
> > > sudo: no valid sudoers sources found, quitting

**Comment by KaidenP** [comment]
What's `cat /etc/sudoers /etc/sudoers.d/*`?

**Comment by ROunofF** [comment]
There's no way for me to know as I can't use sudo and I guess root doesn't have a password set

**Comment by KaidenP** [comment]
So boot up in a live-usb environment and do it. There is obviously a problem in your sudoers file.

You may be able to `gksu`, however I am unsure of this.
